<a href="https://colab.research.google.com/github/himanshusharma-csit/pytorch_tutorial/blob/master/extras/exercises/00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
# Import torch
import torch

# Create random tensor
random_tensor = torch.rand(size=[7,7])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
# Create another random tensor
another_tensor = torch.rand(size=[1,7])

# Perform matrix multiplication
# Using @ and matmul
result_1 = random_tensor @ another_tensor.T
result_2 = random_tensor.matmul(another_tensor.T)
result_3 = torch.matmul(random_tensor, another_tensor.T)

print(result_1)
print(result_2)
print(result_3)

tensor([[2.2408],
        [2.2052],
        [1.4206],
        [2.9522],
        [2.3241],
        [3.0347],
        [3.1296]])
tensor([[2.2408],
        [2.2052],
        [1.4206],
        [2.9522],
        [2.3241],
        [3.0347],
        [3.1296]])
tensor([[2.2408],
        [2.2052],
        [1.4206],
        [2.9522],
        [2.3241],
        [3.0347],
        [3.1296]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [5]:
# Set manual seed
torch.manual_seed(11)

# Create two random tensors
tensor_A = torch.rand(size=[7,7])
tensor_B = torch.rand(size=[1,7])

# Matrix multiply tensors
# Using @ and matmul
result_1 = random_tensor @ another_tensor.T
result_2 = random_tensor.matmul(another_tensor.T)
result_3 = torch.matmul(random_tensor, another_tensor.T)

print(result_1)
print(result_2)
print(result_3)

tensor([[2.2408],
        [2.2052],
        [1.4206],
        [2.9522],
        [2.3241],
        [3.0347],
        [3.1296]])
tensor([[2.2408],
        [2.2052],
        [1.4206],
        [2.9522],
        [2.3241],
        [3.0347],
        [3.1296]])
tensor([[2.2408],
        [2.2052],
        [1.4206],
        [2.9522],
        [2.3241],
        [3.0347],
        [3.1296]])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
# Set random seed on the GPU
torch.cuda.manual_seed(11)



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [1]:
# Set random seed
import torch

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

# Create two random tensors on GPU
random_tensor_A = torch.rand(size=[2,3], device=device)
random_tensor_B = torch.rand(size=[2,3], device=device)

print(random_tensor_A, random_tensor_B)

Device: cuda
tensor([[0.4355, 0.8916, 0.1721],
        [0.1045, 0.8347, 0.8282]], device='cuda:0') tensor([[0.6428, 0.9113, 0.2163],
        [0.7659, 0.8035, 0.4967]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [2]:
# Perform matmul on tensor_A and tensor_B
result_1 = random_tensor_A @ random_tensor_B.T
result_2 = random_tensor_A.matmul(random_tensor_B.T)
result_3 = torch.matmul(random_tensor_A, random_tensor_B.T)

print(result_1, result_2, result_3)

tensor([[1.1296, 1.1353],
        [1.0070, 1.1621]], device='cuda:0') tensor([[1.1296, 1.1353],
        [1.0070, 1.1621]], device='cuda:0') tensor([[1.1296, 1.1353],
        [1.0070, 1.1621]], device='cuda:0')


### 8. Find the maximum and minimum values of the output of 7.

In [5]:
# Find max
max_1 = result_1.max()
max_2 = torch.max(result_1)
print("Max: ", max_1, max_2)

# Find min
min_1 = result_1.min()
min_2 = torch.min(result_1)
print("Min: ", min_1, min_2)

Max:  tensor(1.1621, device='cuda:0') tensor(1.1621, device='cuda:0')
Min:  tensor(1.0070, device='cuda:0') tensor(1.0070, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [7]:
# Find arg max
max_arg1 = result_1.argmax()
max_arg2 = torch.argmax(result_1)
print("Arg Max: ", max_arg1.item(), max_arg2.item())

# Find arg min
min_arg1 = result_1.argmin()
min_arg2 = torch.argmin(result_1)
print("Arg Min: ", min_arg1.item(), min_arg2.item())

Arg Max:  3 3
Arg Min:  2 2



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [8]:
# Set seed
torch.cuda.manual_seed(11)

# Create random tensor
random_tensor_A = torch.rand(size=[1,1,1,10])

# Remove single dimensions
squeezed_tensor = torch.squeeze(random_tensor_A)

# Print out tensors and their shapes
print("Original Tensor Shape: ", random_tensor_A.shape)
print("Squeezed Tensor Shape: ", squeezed_tensor.shape)

Original Tensor Shape:  torch.Size([1, 1, 1, 10])
Squeezed Tensor Shape:  torch.Size([10])
